name: Deploy Webpages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Clone submodule
        run: git submodule update --init --recursive
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          hugo-version: 0.71.1
          extended: true
      - name: Build Hugo
        run: hugo -v
