name: Deploy Webpages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: Clone submodule
        run: git submodule update --init --recursive
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.79.0
          extended: true
      - name: Build Hugo
        run: hugo -v
      - name: git status
        run: git status -uno --porcelain
      - name: reset jsconfig.json
        run: git checkout assets/jsconfig.json
      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_HOST }}
            port: ${{ secrets.FTP_PORT }}
            password: ${{ secrets.FTP_PASSWORD }}
            local_path: './public/*'
            remote_path: './htdocs-ssl'
            sftp_only: true
